spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewservice_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  application:
    name: review-service

security:
  jwt:
    secret: YOUR_SECRET


server:
  port: 8082

app:
  users:
    url: http://localhost:8081
  books:
    url: http://localhost:8080
