spring:
  application:
    name: recommendation-service

server:
  port: 8083

security:
  jwt:
    secret: YOUR_SECRET

app:
  books:
    url: http://localhost:8080
  reviews:
    url: http://localhost:8082