spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  application:
    name: user-service

server:
  port: 8081
