spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  application:
    name: user-service

security:
  jwt:
    secret: YOUR_GENERATED_SECRET
    ttl-seconds: 900

server:
  port: 8081
